ALTER TABLE "Character"
  ALTER COLUMN "itemLevel" TYPE DOUBLE PRECISION,
  ADD COLUMN "serverName" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "combatPower" INTEGER,
  ADD COLUMN "isMain" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "lastSyncedAt" TIMESTAMP(3);
